name: Build and Run Tests
on:
  pull_request:
    types: ['edited', 'opened', 'reopened', 'synchronize']
  push:
    branches: ['main']

jobs:
  build_matrix:
    name: Run tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-20.04
          - name: windows
            os: windows-2019
          - name: macos
            os: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'
      - run: go test
      - run: go build